CREATE TABLE student(
    student_id integer primary key generated by default as identity,
    name varchar(50) not null ,
    surname varchar(50) not null
);
create TABLE course(
    course_id integer primary key generated by default as identity ,
    name varchar(50)
);
create table student_course(
    student_id integer references student(student_id),
    course_id integer references course(course_id),
    primary key (student_id,course_id)
);
create table grade(
    grade_id integer generated by default as identity ,
    value integer not null ,
    student_id integer references student(student_id)on DELETE cascade ,
    course_id integer references course(course_id)on DELETE cascade
);
insert into student(name, surname) values ('Jhon','Smith');
insert into course(name) VALUES ('Math');

