CREATE TABLE student(
    student_id integer primary key generated by default as identity,
    name varchar(50) not null ,
    surname varchar(50) not null,
    course_id integer
);
create TABLE course(
    course_id integer primary key generated by default as identity ,
    name varchar(50),
    student_ID integer
);
create table student_course(
    student_id integer references student(student_id),
    course_id integer references course(course_id),
    primary key (student_id,course_id)
);
create table grade(
    grade_id integer generated by default as identity ,
    value integer not null ,
    student_id integer references student(student_id) on DELETE cascade ,
    course_id integer references course(course_id)on DELETE cascade
);
insert into student(name, surname, course_id) values ('Jhon','Smith',1);
insert into course(name, student_ID) VALUES ('Math',1);
insert into student_course(student_id, course_id) values (1,1);
insert into grade("value", student_id, course_id) values (3,1,1);

